# Pandas for Data Manipulation

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("/Users/sanasalim/Downloads/Day 4/Titanic-Dataset.csv")

### Explore data

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [8]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [9]:
df.shape

(891, 12)

### Filter and select data

Filter by age and survival

In [10]:
alive_babies = df[(df["Age"]<3) & (df["Survived"] == 1)]
print(alive_babies.head())
alive_babies.shape

     PassengerId  Survived  Pclass                            Name     Sex  \
78            79         1       2   Caldwell, Master. Alden Gates    male
172          173         1       3    Johnson, Miss. Eleanor Ileen  female
183          184         1       2       Becker, Master. Richard F    male
305          306         1       1  Allison, Master. Hudson Trevor    male
340          341         1       2  Navratil, Master. Edmond Roger    male

      Age  SibSp  Parch  Ticket      Fare    Cabin Embarked
78   0.83      0      2  248738   29.0000      NaN        S
172  1.00      1      1  347742   11.1333      NaN        S
183  1.00      2      1  230136   39.0000       F4        S
305  0.92      1      2  113781  151.5500  C22 C26        S
340  2.00      1      1  230080   26.0000       F2        S

(15, 12)

Filter by sex

In [11]:
sex_filter = df[df["Sex"] == "male"]
print(sex_filter.head())
sex_filter.shape

   PassengerId  Survived  Pclass                            Name   Sex   Age  \
0            1         0       3         Braund, Mr. Owen Harris  male  22.0
4            5         0       3        Allen, Mr. William Henry  male  35.0
5            6         0       3                Moran, Mr. James  male   NaN
6            7         0       1         McCarthy, Mr. Timothy J  male  54.0
7            8         0       3  Palsson, Master. Gosta Leonard  male   2.0

   SibSp  Parch     Ticket     Fare Cabin Embarked
0      1      0  A/5 21171   7.2500   NaN        S
4      0      0     373450   8.0500   NaN        S
5      0      0     330877   8.4583   NaN        Q
6      0      0      17463  51.8625   E46        S
7      3      1     349909  21.0750   NaN        S

(577, 12)

Select certain columns

In [12]:
four_cols = df[["Survived","Name","Sex","Age"]]
four_cols.head()

   Survived                                               Name     Sex   Age
0         0                            Braund, Mr. Owen Harris    male  22.0
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0
2         1                             Heikkinen, Miss. Laina  female  26.0
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0
4         0                           Allen, Mr. William Henry    male  35.0

Select data based on index

In [13]:
# does include 5
df.loc[1:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [14]:
# does not include 5
df.iloc[1:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

Sort by age

In [15]:
df.sort_values(["Age"]).dropna(subset="Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,0,3,"Connors, Mr. Patrick",male,70.50,0,0,370369,7.7500,NaN,Q
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.00,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
851,852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000,A23,S

### Handle missing values

Find number of missing values

In [16]:
print(df.isnull().sum())

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

Fill null values

In [17]:
# NaN takes the value of the next row
df_filledna = df.fillna(method="pad")
# NaN takes the value of the previous row
df_filledna.fillna(method="bfill")

/var/folders/t_/1r0rf0nj71lbvfn8t13yq0zc0000gn/T/ipykernel_53938/741733309.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filledna = df.fillna(method="pad")
/var/folders/t_/1r0rf0nj71lbvfn8t13yq0zc0000gn/T/ipykernel_53938/741733309.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_filledna.fillna(method="bfill")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C85,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C85,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C123,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,C50,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,C148,Q

In [18]:
no_age = df.copy()
no_age["Age"] = no_age["Age"].fillna(0)
#print(df["Age"].loc[888])
#print(no_age["Age"].loc[888])
print(df.tail())
print(no_age.tail())

     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   0.0      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

Drop rows with null values

In [19]:
print(df["Cabin"].head())

0     NaN
1     C85
2     NaN
3    C123
4     NaN
Name: Cabin, dtype: object

In [20]:
no_none = df.dropna()
print(no_none["Cabin"].head())

1      C85
3     C123
6      E46
10      G6
11    C103
Name: Cabin, dtype: object

### Group By Operations

Find average age of survivors

In [21]:
avg_age = df.groupby("Survived")["Age"].mean()
print(avg_age)

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

Find number of men and women who survived

In [22]:
survivors = df.groupby("Sex")["Survived"].sum()
print(survivors)

Sex
female    233
male      109
Name: Survived, dtype: int64

Find number of survivors in each cabin

In [23]:
cabin_survivors = df.groupby("Cabin")["Survived"].sum()
print(cabin_survivors)
cabin_survivors.max()

Cabin
A10    0
A14    0
A16    1
A19    0
A20    1
      ..
F33    3
F38    0
F4     2
G6     2
T      0
Name: Survived, Length: 147, dtype: int64

4

In [24]:
# total number of survivors
print(df[df["Survived"]==1])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
875      0              2667   7.2250   NaN        C
879      1             11767  83.1583   C50        C
880      1            230433  26.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C

[342 rows x 12 columns]

Find average age by passenger class

In [25]:
avg_age_class = df.groupby("Pclass")["Age"].mean()
print(avg_age_class)

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

Find port survival rate

In [26]:
port_survival = df.groupby("Embarked")["Survived"].sum()
port_survival_rate = df.groupby("Embarked")["Survived"].sum()
survived_port = df.groupby("Embarked").size()
print(survived_port)
print(port_survival)
print(port_survival_rate)
print(len(df))

Embarked
C    168
Q     77
S    644
dtype: int64
Embarked
C     93
Q     30
S    217
Name: Survived, dtype: int64
Embarked
C     93
Q     30
S    217
Name: Survived, dtype: int64
891

### Merging and joining

In [27]:
# creating new data frame with same passenger id and new column "Child"
df_id = df[["PassengerId"]].copy()
df_id["Child"] = df["Age"] < 18

print(df_id.loc[171:184])

     PassengerId  Child
171          172   True
172          173   True
173          174  False
174          175  False
175          176  False
176          177  False
177          178  False
178          179  False
179          180  False
180          181  False
181          182  False
182          183   True
183          184   True
184          185   True

In [28]:
df_with_child = pd.merge(df,df_id,on="PassengerId")
df_with_child.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Child
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,False
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,False
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,False
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,False
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,False

In [29]:
df_family = df[["PassengerId"]].copy()
df_family["Family Size"] = df["SibSp"] + df["Parch"] + 1
print(df_family["Family Size"].max())
print(df_family.loc[180])
df_family.tail()

11
PassengerId    181
Family Size     11
Name: 180, dtype: int64

     PassengerId  Family Size
886          887            1
887          888            1
888          889            4
889          890            1
890          891            1

In [30]:
df_with_family = df.join(df_family["Family Size"])
df_with_family.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Family Size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

### Pivot Table

Average age of males and females in each passenger class

In [33]:
pd.pivot_table(df,index="Pclass",values="Age",columns="Sex",aggfunc="mean")

Sex        female       male
Pclass
1       34.611765  41.281386
2       28.722973  30.740707
3       21.750000  26.507589

Counts number of male and female passengers in each class

In [37]:
df.pivot_table(values="PassengerId",index="Pclass",columns="Sex",aggfunc="count")

Sex     female  male
Pclass
1           94   122
2           76   108
3          144   347